const test=require("node:test");const assert=require("node:assert/strict");
const Events=require("../advanced-decision-review-events.js");
function storage(){const m=new Map();return{getItem:k=>m.has(k)?m.get(k):null,setItem:(k,v)=>m.set(k,v)}}
const base={sessionId:"s",reviewId:"r",experienceId:"r",experienceVersion:"sgf-decision-review-item-v1",sourceId:"src",sourcePositionVersion:"sgf-source-position-v1",positionFingerprint:"pos",candidateSetVersion:"board-intersection-attempts-rules-checked-v1",scoringContractVersion:"sgf-decision-review-historical-comparison-v1",evidenceTaxonomyVersion:"sgf-decision-review-evidence-v1",rulesContractVersion:"go-core-simple-ko-v1",boardSize:19,occurredAt:"2026-09-28T12:00:00.000Z"};
test("decision review 首候選與 retry 分開，候選事件不提前保存原著比較",()=>{const s=storage();assert.equal(Events.append(s,{...base,eventId:"p",type:"review_presented",originalMove:null,matchesOriginal:null,originalExposed:false}).ok,true);assert.equal(Events.append(s,{...base,eventId:"f",type:"candidate_first",point:[3,3],legal:true,originalMove:null,matchesOriginal:null,originalExposed:false}).ok,true);assert.equal(Events.append(s,{...base,eventId:"r2",type:"candidate_retry",point:[4,4],legal:true,originalMove:null,matchesOriginal:null,originalExposed:false}).ok,true);const e=Events.read(s).store.events;assert.deepEqual(e.filter(x=>x.type.startsWith("candidate")).map(x=>x.type),["candidate_first","candidate_retry"]);assert.ok(e.filter(x=>x.type.startsWith("candidate")).every(x=>x.originalMove===null&&x.matchesOriginal===null));});
test("與原著不同只記 comparison，不產生 correct/mastery/transfer",()=>{const s=storage();const x=Events.append(s,{...base,eventId:"x",type:"original_revealed",originalMove:[16,3],firstCandidateMatchesOriginal:false,originalExposed:true});assert.equal(x.ok,true);assert.equal("correct" in x.event,false);assert.equal(x.event.formalEligible,false);assert.equal(x.event.transferLevel,null);assert.equal(x.event.mastery,undefined);});
test("authority 或 malformed store fail closed",()=>{const s=storage();assert.equal(Events.append(s,{...base,eventId:"bad",type:"candidate_first",point:[3,3],legal:true,originalMove:[4,4],matchesOriginal:false,originalExposed:false}).ok,false);s.setItem(Events.STORAGE_KEY,"{bad");assert.equal(Events.read(s).ok,false);});

const fs=require("node:fs"),path=require("node:path");
test("進階頁明示 decision review 的 practice-only authority boundary",()=>{const html=fs.readFileSync(path.join(__dirname,"..","advanced.html"),"utf8");assert.match(html,/19×19 棋譜決策點複盤/);assert.match(html,/不把原棋譜當唯一最佳手/);assert.match(html,/不影響能力紀錄、複習安排或正式評量/);assert.match(html,/advanced-decision-review-events\.js\?v=advanced-decision-review-v1/);assert.match(html,/advanced-decision-review\.js\?v=advanced-decision-review-v2/);assert.match(html,/advanced-decision-replay-events\.js\?v=advanced-decision-replay-v1/);assert.match(html,/advanced-decision-replay\.js\?v=advanced-decision-replay-v1/);assert.match(html,/同一個已看過的局面加入重做清單/);});
